### ISSUE TITLE
can't login with default password

### ISSUE THREAD

**Issue by SimonKenyonShepard** [COCOPi/cockpit-docker#4]
Hey,
I tried installing this using latest version of kitematic on my macosx el captain, the image comes up fine and I can get to the login screen but the default password in the install file admin/admin does not work always results in a login failure.

**Comment by SimonKenyonShepard** [comment]
ah ok, wait, I see I need a mongo container running as well, I didn't see this in the documentation maybe good to add it. Thanks

**Comment by andrefreitas** [comment]
You are welcome.

**Comment by SimonKenyonShepard** [comment]
actually, I still couldn't for the life of me get this running.
I downloaded the git repo, and ran docker compose, got the next version, but it still didn't work with password admin/admin. Think there must be something wrong. Did you try doing a fresh install?

**Comment by timaschew** [comment]
Did you open `/install` before trying to login?
