### ISSUE TITLE
Credentials not workin

### ISSUE THREAD

**Issue by MHPtbehrens** [COCOPi/cockpit-docker#5]
Hello,

I somehow gathered that the default credentials for login on the container are admin/admin. Unfortunately this does not work. Any ideas?

Best,
T

**Comment by lchachurski** [comment]
First you need to visit `http://127.0.0.1:8080/install/` or `http://localhost:8080/install/`

**Comment by andrefreitas** [comment]
Please refer to documentation in https://getcockpit.com/docs#!getting_started/setup to setup Cockpit.

Thanks @lchachurski
